import re
import logging
from typing import Dict, Any, List, Tuple, Optional

logger = logging.getLogger(__name__)

class TelemetryValidator:
    """
    Zero-Hallucination Post-LLM Validator.
    Inspects text generated by external models to ensure:
    1. Every reported meteorological metric (temp, wind, precip, uv) strictly matches Open-Meteo telemetry.
    2. Mandated primary SOP ID is cited.
    3. Unauthorized or hallucinated policies (e.g. SOP-999) are rejected.
    """

    @staticmethod
    def validate(
        response_text: str,
        weather: Dict[str, Any],
        primary_sop: Dict[str, Any],
        contributing_sops: Optional[List[Dict[str, Any]]] = None
    ) -> Tuple[bool, List[str]]:
        violations = []
        lower_resp = response_text.lower()
        norm_resp = response_text

        # 1. SOP Traceability Check
        sop_id = (primary_sop or {}).get("id")
        if sop_id and sop_id not in norm_resp:
            violations.append(f"Missing mandatory primary SOP ID citation: [{sop_id}]")

        # Disallowed/Hallucinated SOP check
        allowed_ids = {sop_id} if sop_id else set()
        if contributing_sops:
            for cs in contributing_sops:
                if cs.get("id"):
                    allowed_ids.add(cs["id"])

        cited_sop_ids = set(re.findall(r'\bSOP-\d{3}\b', norm_resp, re.I))
        for cited in cited_sop_ids:
            cited_upper = cited.upper()
            if cited_upper not in allowed_ids and cited_upper != "SOP-000":
                violations.append(f"Response cited unauthorized or hallucinated policy: [{cited_upper}]")

        # 2. Telemetry Verification
        # Check Temperature
        actual_temp = weather.get("temperature_2m")
        actual_app_temp = weather.get("apparent_temperature", actual_temp)
        temp_patterns = [
            r'(-?\d+(?:\.\d+)?)\s*(?:°\s*c|degrees?\s*(?:celsius|c)\b)',
            r'temperature(?: of| is|:)?\s*(-?\d+(?:\.\d+)?)'
        ]
        extracted_temps = []
        for pat in temp_patterns:
            for m in re.finditer(pat, lower_resp):
                try:
                    extracted_temps.append(float(m.group(1)))
                except ValueError:
                    pass

        valid_temps = []
        if actual_temp is not None:
            valid_temps.append(float(actual_temp))
        if actual_app_temp is not None:
            valid_temps.append(float(actual_app_temp))

        for t in extracted_temps:
            # Check if within tolerance of 1.0 degree from either actual or apparent temp
            is_valid = any(abs(t - vt) <= 1.0 for vt in valid_temps)
            # Or if it matches a threshold mentioned in primary SOP
            if not is_valid and primary_sop:
                triggers = primary_sop.get("triggers", {})
                for k, v in triggers.items():
                    if "temp" in k and isinstance(v, (int, float)) and abs(t - float(v)) <= 0.5:
                        is_valid = True
                        break
            if not is_valid and valid_temps:
                violations.append(f"Unverified temperature cited: {t}°C (Actual: {actual_temp}°C, Apparent: {actual_app_temp}°C)")

        # Check Wind Speed (km/h)
        actual_wind = weather.get("wind_speed_10m")
        actual_gusts = weather.get("wind_gusts_10m", actual_wind)
        wind_patterns = [
            r'(\d+(?:\.\d+)?)\s*km/h',
            r'wind(?: speed| gusts)?(?: of| is|:)?\s*(\d+(?:\.\d+)?)'
        ]
        extracted_winds = []
        for pat in wind_patterns:
            for m in re.finditer(pat, lower_resp):
                try:
                    extracted_winds.append(float(m.group(1)))
                except ValueError:
                    pass

        valid_winds = []
        if actual_wind is not None:
            valid_winds.append(float(actual_wind))
        if actual_gusts is not None:
            valid_winds.append(float(actual_gusts))

        for w in extracted_winds:
            is_valid = any(abs(w - vw) <= 1.5 for vw in valid_winds)
            if not is_valid and primary_sop:
                triggers = primary_sop.get("triggers", {})
                for k, v in triggers.items():
                    if "wind" in k and isinstance(v, (int, float)) and abs(w - float(v)) <= 0.5:
                        is_valid = True
                        break
            if not is_valid and valid_winds:
                violations.append(f"Unverified wind figure cited: {w} km/h (Actual: {actual_wind} km/h, Gusts: {actual_gusts} km/h)")

        # Check Precipitation (mm)
        actual_precip = weather.get("precipitation")
        precip_patterns = [
            r'(\d+(?:\.\d+)?)\s*mm\b',
            r'precipitation(?: of| is|:)?\s*(\d+(?:\.\d+)?)'
        ]
        extracted_precips = []
        for pat in precip_patterns:
            for m in re.finditer(pat, lower_resp):
                try:
                    extracted_precips.append(float(m.group(1)))
                except ValueError:
                    pass

        if actual_precip is not None:
            val_p = float(actual_precip)
            for p in extracted_precips:
                is_valid = (abs(p - val_p) <= 1.0)
                if not is_valid and primary_sop:
                    triggers = primary_sop.get("triggers", {})
                    for k, v in triggers.items():
                        if "precip" in k and isinstance(v, (int, float)) and abs(p - float(v)) <= 0.5:
                            is_valid = True
                            break
                if not is_valid:
                    violations.append(f"Unverified precipitation figure cited: {p} mm (Actual: {val_p} mm)")

        is_passed = (len(violations) == 0)
        return is_passed, violations
